<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog" Version="4.3.1" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Stubble.Core" Version="1.10.8" />
		<PackageReference Include="Wkhtmltopdf.NetCore" Version="3.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="wkhtmltopdf\Windows\wkhtmltopdf.exe">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
